### ISSUE TITLE
Polaridad motores

### ISSUE THREAD

**Issue by amarsal3** [thar/velocistaEdu#2]
Cuando la polaridad de los motores no es la deseada ahora se puede poner una orden. Qué tal incluirlo como parámetro en la función inicializar?
void VelocistaEdu::inicializar(boolean polaridad_motor_derecho, boolean polaridad_motor_izquierdo).

0 --> polaridad normal
1--> polaridad invertida

**Comment by thar** [comment]
He reescrito toda la interfaz de la librería. Creo que ahora es más clara. Uno de los cambios tiene que ver precisamente con la seleccion de la polaridad.
Para poder seleccionar la polaridad, en caso de que esté cambiada, basta con pasarle los parametros necesarios a la función "obtenerRobot" de la librería.
En el ejemplo "movimientoRuedas" (examples/movimientoRuedas/movimientoRuedas.ino) se ve claramente como se puede cambiar la polaridad de los motores.
